//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task_5_2
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Task_CRUD
    {
        public int Id { get; set; }
        public string farst_Name { get; set; }
        public string Last_Name { get; set; }
        public string Email { get; set; }
        public Nullable<int> Phone { get; set; }
        public Nullable<int> Age { get; set; }
        public string Job_Title { get; set; }
        public Nullable<bool> Gender { get; set; }
        public string image { get; set; }
        public string CV { get; set; }
        [NotMapped]
        public HttpPostedFileBase ImageFile { set; get; }
    }
}
